version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  pack:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm pack --dry-run

  test:
    parameters:
      os:
        type: executor
      node-version:
         type: string
    executor: << parameters.os >>
     steps:
       - checkout
       - node/install:
          node-version: << parameters.node-version >>

workflows:
  simple:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                # https://circleci.com/developer/images/image/cimg/node
                - 'current'
                - 'lts'
                - '16.19.1'
                - '14.21.3'
      - pack:
          requires:
            - node/test

      - test:
          matrix:
            parameters:
              os: [docker, linux, macos]
              node-version: ["current", "lts"]