version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  pack:
    docker:
      - image: cimg/node:18.14.0
    steps:
      - checkout
      - run: npm run build
      - run: npm pack --dry-run

workflows:
  simple:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                # https://circleci.com/developer/images/image/cimg/node
                - '19.6.0'
                - '18.14.0'
                - '16.19.0'
      - pack:
          requires:
            - node/test
