version: 2.1

orbs:
  node: circleci/node@5.1.0

workflows:
  simple:
    jobs:
      - node/test:
          # Relevant tags can be found on https://circleci.com/developer/images/image/cimg/node
          version: '18.14'
          pkg-manager: npm
      - node/pack:
          version: '18.14'
          pkg-manager: npm
