version: 2.1

orbs:
  node: circleci/node@5.1.0

workflows:
  simple:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                # https://circleci.com/developer/images/image/cimg/node
                - '19.6.0'
                - '18.14.0'
                - '16.19.0'